/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#1c1b1b",
        "error": "#ffb4ab",
        "surface": "#131313",
        "surface-dim": "#131313",
        "on-tertiary-fixed-variant": "#004e5d",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#72d4ef",
        "success-teal": "#14B8A6",
        "on-background": "#e5e2e1",
        "surface-100": "#18181B",
        "primary-fixed-dim": "#ffb4ac",
        "surface-container-lowest": "#0e0e0e",
        "on-secondary-fixed-variant": "#004395",
        "secondary-fixed-dim": "#adc6ff",
        "border-subtle": "rgba(255, 255, 255, 0.08)",
        "surface-200": "#27272A",
        "on-primary-fixed": "#410002",
        "on-error": "#690005",
        "surface-container-highest": "#353534",
        "on-tertiary-fixed": "#001f27",
        "on-primary-fixed-variant": "#93000d",
        "surface-bright": "#3a3939",
        "on-tertiary-container": "#002e39",
        "error-container": "#93000a",
        "inverse-primary": "#bb171c",
        "outline-variant": "#5b403d",
        "surface-container-high": "#2a2a2a",
        "primary-container": "#ff544c",
        "tertiary-fixed": "#afecff",
        "inverse-surface": "#e5e2e1",
        "on-surface-variant": "#e4beb9",
        "surface-tint": "#ffb4ac",
        "surface-container": "#201f1f",
        "secondary": "#adc6ff",
        "on-secondary-fixed": "#001a42",
        "on-primary-container": "#5c0005",
        "warning-amber": "#F59E0B",
        "on-primary": "#690006",
        "tertiary-container": "#319db6",
        "primary": "#ffb4ac",
        "surface-variant": "#353534",
        "on-surface": "#e5e2e1",
        "tertiary": "#72d4ef",
        "on-secondary-container": "#e6ecff",
        "muted-gray": "#6B7280",
        "secondary-container": "#0566d9",
        "on-secondary": "#002e6a",
        "outline": "#ab8985",
        "on-tertiary": "#003641",
        "secondary-fixed": "#d8e2ff",
        "primary-fixed": "#ffdad6",
        "inverse-on-surface": "#313030",
        "background": "#131313"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "0.5rem",
        "gutter": "1.5rem",
        "xs": "0.25rem",
        "lg": "1.5rem",
        "margin-desktop": "2.5rem",
        "xl": "2rem",
        "base": "4px",
        "md": "1rem",
        "margin-mobile": "1rem"
      },
      fontFamily: {
        "label-status": ["Inter"],
        "display-countdown": ["JetBrains Mono"],
        "body-md": ["Inter"],
        "headline-md": ["DM Sans"],
        "headline-lg-mobile": ["DM Sans"],
        "headline-lg": ["DM Sans"],
        "label-caps": ["JetBrains Mono"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "label-status": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "display-countdown": ["48px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
        "label-caps": ["12px", {"lineHeight": "16px", "fontWeight": "600"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      },
      animation: {
        'fadeIn': 'fadeIn 0.3s ease-in-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
}
